[tool.ruff]
line-length = 120
exclude = ["build", "dist", ".venv"]
fix = true

[tool.ruff.lint]
select = ["E", "F", "I"]

[tool.pytest.ini_options]
filterwarnings = [
    "ignore::DeprecationWarning:stempeg.*"
]